### ISSUE TITLE
Failed to run Publish action

### ISSUE THREAD

**Issue by glapa-grossklag** [glapa-grossklag/tree-sitter-elsa#4]
Not certain of the cause, @amaanq can you investigate? Could be my fault.

https://github.com/glapa-grossklag/tree-sitter-elsa/actions/runs/4039101232/workflow

**Comment by amaanq** [comment]
oops, i deleted the build portion since that was (and still sort-of is) redundant, but the ci actions "needs" build, and i guess its ok to keep there since this could potentially not run at the same time as the normal ci action. I'll readd that in a sec

**Comment by amaanq** [comment]
@glapa-grossklag  Might be good to tag the last commit as v1.0.0 and then push the commit so that the publish actions are run. You can do like so

```bash
git tag v1.0.0

git push --tags
```

**Comment by glapa-grossklag** [comment]
> Might be good to tag the last commit as v1.0.0 and then push the commit so that the publish actions are run.

@amaanq Already tagged a commit as [v1.0.0](https://github.com/glapa-grossklag/tree-sitter-elsa/releases/tag/v1.0.0). Should I increment or keep?

I also ran the publish action manually.
